[tool.poetry]
name = "pretix-wrapper"
version = "0.1.0"
description = ""
authors = ["adisbladis <adisbladis@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pretix = "^2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
